### ISSUE TITLE
 pre-split files

### ISSUE THREAD

**Issue by aixiaobaikkk** [xmed-lab/DHC#2]
Hello author, it seems that the pre-split file is not provided in the code. Can you provide it?

**Comment by McGregorWwww** [comment]
Hi, thanks for attention, the pre-split files have been uploaded.

Btw, if you're interested, we highly recommend you try our new work: https://github.com/xmed-lab/GenericSSL, which considers more practical scenarios of semi-supervised segmentation.

Good luck with your research.
