### ISSUE TITLE
Questions Regarding Spynase Dataset Split and Result Discrepancies

### ISSUE THREAD

**Issue by lzhang30** [xmed-lab/DHC#4]
Hello,

First of all, I'd like to extend my gratitude for your open-source project. It has significantly aided my research. I am writing to seek clarification regarding certain aspects of the Synapse dataset segmentation.

To begin with, I have a preliminary question regarding the order of classes: Is the order of classes shown in the logs the same as the one presented in the tables in your paper? If they are the same, I have observed a notable discrepancy in the data of the fourth column. If they differ, could you please specify the order of classes as they appear in the log output?

Moving on to more specific queries:

1. Concerning the Synapse dataset used in your project, is it identical to the RawData.zip found in the BTCV dataset? I encountered a hurdle while executing your `preprocess.py` script, as I couldn't locate an `imagesTr` folder in the raw data. Subsequently, I downloaded the data from the link you [provided](https://hkustconnect-my.sharepoint.com/personal/hwanggr_connect_ust_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fhwanggr%5Fconnect%5Fust%5Fhk%2FDocuments%2Fsynapse%5Fdata) and modified the code in `evaluate_Ntimes.py` as shown in the attached image. However, this led to a size mismatch due to the patch-size settings in your preprocessing script (as seen in the attached image). The expected resize shape through this code should be (80,160,160), causing a size mismatch error (details in the attached image), since the size of the prediction inferred from `test.py` may be in a similar shape as the image volume (72,144,144).

Following this, I conducted two experiments with different shapes: one with the raw data from RawData.zip resized to 80,160,160, and another used the data downloaded from one-drive in the shape of  72,144,144. The results of these experiments are attached. While the results for other columns were quite close, there was a significant variance in the results of the fourth column, even when tested on datasets of 40% and 20% using the split you provided.

I am keen to understand these discrepancies and would greatly appreciate your insights or any guidance you could provide.
Thanks again for your wonderful open-source project!

mismatch error:

The patch-size set in preprocess was  
![image](https://github.com/xmed-lab/DHC/assets/141390154/3d748d56-d382-4181-adee-ad7465553cd8),
and the resize-shape through this code should be like (80,160,160), cause the error of size mis-match
![image](https://github.com/xmed-lab/DHC/assets/141390154/bb2ba226-32b5-4061-9eaa-2cf54ee8f24d)
because the size of the pred inffered from test.py may in the same shape like the image volume as (72,144,144).

Result: (in 20% synapse dataset)
in  80,160,160:
![image](https://github.com/xmed-lab/DHC/assets/141390154/2788320f-3955-4d90-82f9-96862856ad07)
in 72,144,144
![image](https://github.com/xmed-lab/DHC/assets/141390154/6df782d3-c7d4-415f-9355-f5abbe29f1f2)
Futher more, I trained fully-Vnet by using` python ./code/train_fully.py `, and I got the result like this:
![image](https://github.com/xmed-lab/DHC/assets/141390154/d8ad6caf-0331-4c3c-9340-6d1034119429)
It is a little far form the full-VNet's result in the paper.

**Comment by McGregorWwww** [comment]
Thanks for your attention and pointing out the issue. Actually, it is the code version issue, since when we conducted the AMOS experiment, we changed a lot of the code. Now we update several scripts and the pre-processed data. Please download them again and sorry for the inconvenience.

As for the fully supervised performance, maybe you can change the epoch to 800, thus the performance will be more stable.
