### ISSUE TITLE
May I kindly ask you for correcting your codes

### ISSUE THREAD

**Issue by Chenzhgit** [xmed-lab/DHC#9]
Dear Author,
I appreciate you so much that you released your awesome work for helping others' work improvement. 
1. Actually, your following modified codes in **code/utils/__init__.py** cannot run successfully when running **test.py** after using command **bash train3times_seeds_20p.sh -c 0 -t synapse -m dhc -e '' -l 3e-2 -w 0.1**. Could you please spare a little bit time for checking the modified files?
 
![image](https://github.com/xmed-lab/DHC/assets/121877807/ce87d4bc-ed17-4a68-96f8-33923a1c273d)

2. I reproduced your dhc work with your previous unchanged **code/utils/__init__.py** and **your recently uploaded synapse .npy files(images, labels and processed files)**. The reproduced results are higher than those in your published article. Is there something wrong with my reproduction?
![image](https://github.com/xmed-lab/DHC/assets/121877807/25cae242-18fb-422e-8789-220f60b3420f)

3. I try to **only use labeled images**, for example, **40% labeled images but without the remaining unlabeled images** for dhc traning. The segmentation accuracy is higher than combining labeled and unlabeled data by using less time with same configurations. It means that the semi-supervised methods **dhc** result in lower accuracy and longer training time. Is there a problem with my implementations? 
![image](https://github.com/xmed-lab/DHC/assets/121877807/d5e8f4b9-9745-4875-b4b4-eabaeeaca393)
![image](https://github.com/xmed-lab/DHC/assets/121877807/29000762-057a-4426-862f-345a8b11955e)

4. For reproduction of every time, the reproduced mean result of 3 folds is very different (The difference between the highest and lowest is about 1.5 percentage points, showed in question 2). So how should I choose the result for comparison, choose the lowest reproduced result or the highest result, or something average? But next time, the reproduced results are different again, if I reproduce you method more times. 
Please give me a helping hand. Thank you so much.^^ @McGregorWwww

**Comment by McGregorWwww** [comment]
Hello, thank you for conducting these constructive tests. I'm currently occupied with preparing a conference rebuttal. Once I am free from this task, I'll thoroughly review the code. Apologize for any inconvenience this may cause.

**Comment by McGregorWwww** [comment]
Hi, sorry for the delay. I've reviewed the code and fixed the bugs, you can download the code and the new preprocessed Synapse data now. For Q2&3, the reason is that the preprocessed data is not correct, it should not be in the shape (80, 160,160). For Q4, this issue is quite annoying and it may be mainly due to the limited data and the randomness, even if we set random seed. I think it is fine that you report the highest results.
